"""
Content watermarking and provenance tracking for generated content.
"""

from app.models.content_models import MultiPlatformContent

WATERMARK_COMMENT = "<!-- Generated by GNONE AI Pipeline [v1.0] -->"
PROVENANCE_HEADER = "X-Content-Source"


def inject_watermark(html_body: str, pipeline_id: str) -> str:
    if WATERMARK_COMMENT in html_body:
        return html_body
    return html_body + "\n" + WATERMARK_COMMENT


def inject_provenance_header(content: MultiPlatformContent, metadata: dict) -> MultiPlatformContent:
    provenance_value = (
        f"gnone-pipeline; "
        f"pipeline_id={metadata.get('pipeline_id', 'unknown')}; "
        f"client_id={metadata.get('client_id', 'unknown')}; "
        f"v=1.0"
    )

    current_html = content.blogspot.html_body
    if PROVENANCE_HEADER.lower() not in current_html.lower():
        content.blogspot.html_body = (
            f"<!-- {PROVENANCE_HEADER}: {provenance_value} -->\n"
            + current_html
        )
    return content


def verify_provenance(content: str) -> bool:
    return WATERMARK_COMMENT in content
