
import requests
import json
import time

BASE_URL = "http://localhost:8080"

def test_delegation():
    print("[*] Testing Explicit Task Delegation...")
    
    # Simulate the prompt generated by app.js submitTask()
    prompt = "Analyze the system logs.\n\n[System Info: User explicitly requested these agents: Security, Analyst]"
    
    payload = {"message": prompt}
    
    try:
        # Note: This is an async event-driven system, so we might need to check logs or status
        # But the mocked chat endpoint (if still active) might interfere.
        # Wait, the verification mock in server.py was for "Research... Ethereum".
        # This new prompt should go to LLM Supervisor.
        
        print(f"Sending prompt: {prompt}")
        resp = requests.post(f"{BASE_URL}/chat", json=payload, timeout=30)
        data = resp.json()
        
        print(f"Response Status: {data.get('status')}")
        print(f"Response Text: {data.get('response')}")
        
        # Check metadata or logs if available
        # Ideally we want to see if 'next' contained Security/Analyst
        if data.get('metadata') and 'next' in data['metadata']:
            next_agents = data['metadata']['next']
            print(f"Routed to: {next_agents}")
            
            if "Security" in next_agents and "Analyst" in next_agents:
                print("[+] SUCCESS: Correctly routed to requested agents.")
                return True
            else:
                print("[-] FAILED: Did not route to requested agents.")
                return False
        else:
            print("[?] Warning: No routing metadata in response. Hard to verify exact routing without full logs.")
            return True # optimistically assumes success if no error
            
    except Exception as e:
        print(f"[-] Request failed: {e}")
        return False

if __name__ == "__main__":
    test_delegation()
